// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFw5HIIQYuXMXfDt7uPLaVFDtVagMV64',
    appId: '1:568186916298:web:9c106e0aa0ecaf8a1e5333',
    messagingSenderId: '568186916298',
    projectId: 'flash-chat-by-ayeni',
    authDomain: 'flash-chat-by-ayeni.firebaseapp.com',
    storageBucket: 'flash-chat-by-ayeni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLOj5GHozacSDrdF2AQPUuVW9zyI75iM',
    appId: '1:568186916298:android:5a7899bac3207e3a1e5333',
    messagingSenderId: '568186916298',
    projectId: 'flash-chat-by-ayeni',
    storageBucket: 'flash-chat-by-ayeni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0SRiJstZoFz9egVJMl4AkHPLOjw55O3U',
    appId: '1:568186916298:ios:b6da9f13a5a6adae1e5333',
    messagingSenderId: '568186916298',
    projectId: 'flash-chat-by-ayeni',
    storageBucket: 'flash-chat-by-ayeni.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0SRiJstZoFz9egVJMl4AkHPLOjw55O3U',
    appId: '1:568186916298:ios:45f94c837e30ac0e1e5333',
    messagingSenderId: '568186916298',
    projectId: 'flash-chat-by-ayeni',
    storageBucket: 'flash-chat-by-ayeni.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
